name: GRE-fe CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  VITE_REACT_APP_API_BASE_URL: ${{ secrets.VITE_REACT_APP_API_BASE_URL }}
  VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  CLIENT_ID_M2M: ${{ secrets.CLIENT_ID_M2M }}
  CLIENT_SECRET_M2M: ${{ secrets.CLIENT_SECRET_M2M }}
  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
  VITE_AUDIENCE: ${{ secrets.VITE_AUDIENCE }}
  VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
  VITE_LOGIN_API: ${{ secrets.VITE_LOGIN_API }}
  VITE_TOKEN_API: ${{ secrets.VITE_TOKEN_API }}
  VITE_MAIN_URI: ${{ secrets.VITE_MAIN_URI }}
  VITE_LOGOUT_URI: ${{ secrets.VITE_LOGOUT_URI }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependences
        run: npm install

      - name: Run ESLint and Prettier
        run: npm run lint

      - name: Run formatters
        run: npm run format

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      # - name: Upload coverage report to Coveralls
      #   uses: coverallsapp/github-action@v2.2.3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
